### ISSUE TITLE
CUDA Error: invalid device ordinal

### ISSUE THREAD

**Issue by wilke** [JDACS4C-IMPROVE/SWnet#7]
Building and testing container in SWnet repo

Host: lambda7

Steps:

1. `singularity build --fakeroot SWnet.sif SWnet.def`
2. `singularity run --nv --bind `pwd`/tmp:/candle_data_dir SWnet.sif train.sh 1 /candle_data_dir --epochs 1`

Output:

```
 'CN1CCC(CC1)COC2=C(C=C3C(=C2)N=CN=C3NC4=C(C=C(C=C4)Br)F)OC']
The preprocess of CCLE dataset has finished!
CCLE drug similarity has finished!
-----------------------------------------------------------
dataset size:  (9767, 3) (543, 3) (543, 3)
-----------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/SWnet/SWnet_CCLE_baseline_pytorch.py", line 714, in <module>
    scores = run(gParameters)
  File "/usr/local/SWnet/SWnet_CCLE_baseline_pytorch.py", line 634, in run
    model_ft = model_ft.cuda(device=device_ids[0])  #
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 689, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 579, in _apply
    module._apply(fn)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 602, in _apply
    param_applied = fn(param)
  File "/opt/conda/lib/python3.7/site-packages/torch/nn/modules/module.py", line 689, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
```

_Originally posted by @wilke in https://github.com/JDACS4C-IMPROVE/SWnet/issues/6#issuecomment-1734468042_

**Comment by rajeeja** [comment]
possibly fixed by #8
